[build]
  publish = "build/"
  command = "CI=false npm run build"

[build.processing]
    skip_processing = true

[[headers]]
  for = "/static/media/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/static/media/*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/static/media/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/static/media/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-eot"
