[build]
  publish = "build/"
  command = "npm run build"

[build.processing]
    skip_processing = true

[[headers]]
  for = "/src/fonts/Mazzard/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/src/fonts/Mazzard/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/src/fonts/Mazzard/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/src/fonts/Mazzard/*.eot"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-eot"
